
		<footer class="footer-container">
			<div class="left-col">
				<!-- <img class="logo-footer" src="assets/img/logo.png" alt="KA Serviços Contábeis"> -->
				<div class="social-media">
					<a href="https://www.facebook.com/kaservicoscontabeis" target="_blank"><i class="fab fa-facebook"></i></a>
					<a href="https://www.instagram.com/kaservicos" target="_blank"><i class="fab fa-instagram"></i></a>
					<a href="https://www.youtube.com/channel/UCC3AT3cECO7uCRu7gdoyVhw" target="_blank"><i class="fab fa-youtube"></i></a>
					<a href="https://www.linkedin.com.br/company/kaservicos" target="_blank"><i class="fab fa-linkedin-in"></i></a>
				</div>
			</div>

			<div class="right-col"></div>
			<p class="rights-text"> 2020 Criado por 7K Tecnologia e Marketing - Todos os direitos reservados	
				</p>
		</footer>