
		<footer class="footer-container">
			<div class="left-col">
				<!-- <img class="logo-footer" src="assets/img/logo.png" alt="KA Serviços Contábeis"> -->
				<div class="social-media">
					<a href="#"><i class="fab fa-facebook"></i></a>
					<a href="#"><i class="fab fa-instagram"></i></a>
					<a href="#"><i class="fab fa-youtube"></i></a>
					<a href="#"><i class="fab fa-linkedin-in"></i></a>
				</div>
		<a href="#"><h4>Área do Cliente</h1></a>
			</div>

			<div class="right-col"></div>
			<p class="rights-text"> 2020 Criado por 7K Tecnologia e Marketing - Todos os direitos reservados	
				</p>
		</footer>