<footer class="footer-container">
			<div class="right-col">
				<!-- <img class="logo-footer" src="../assets/img/logo.png" alt="KA Serviços Contábeis"> -->
				<div class="social-media">
					<a href="https://www.facebook.com/kaservicoscontabeis" target="_blank"><i class="fab fa-facebook"></i></a>
					<a href="https://www.instagram.com/kaservicos" target="_blank"><i class="fab fa-instagram"></i></a>
					<a href="https://www.youtube.com/channel/UCC3AT3cECO7uCRu7gdoyVhw" target="_blank"><i class="fab fa-youtube"></i></a>
					<a href="https://www.linkedin.com.br/company/kaservicos" target="_blank"><i class="fab fa-linkedin-in"></i></a>
				</div>


			</div>

			<div class="left-col">
			<div class="rights-text"> 
				<div class="icons-footer">
					<i class="fas fa-map-marker-alt icons-text"></i><p> Edf. Stock Center - Av. Luís Viana, nº 2489, Sala 8C, Paralela - Salvador - BA</p>
				</div>
				<div class="icons-footer">
					<i class="fas fa-phone-square-alt icons-text"></i><p>(71) 3013 4617/ 3322 0908</p>
				</div>
				<div class="icons-footer">
					<i class="fas fa-envelope icons-text"></i><p> contato@kaservicos.com.br</p>
				</div>
				<div class="icons-footer">
					<i class="fas fa-clock icons-text"></i><p> Atendimento: 8h às 18h</p>
				</div>  


			</div>
			</div>
		</footer>