<header>
	<div class="header">
		<img src="../assets/img/kalogo.png" class="logo">

		<button class="button-proposal">Solicitar Proposta</button>
		<input type="checkbox" id="checkbox">	
		<label for="checkbox" class="show-menu-botton">
			<i class="fas fa-bars"></i>
		</label>

		<ul class="menu">
			<a href="#">HOME</a>
			<a href="#box-tecs">SOBRE NÓS</a>
			<a href="#services">SERVIÇOS</a>
			<a href="#">CASES</a>
			<a href="#">BLOG</a>
			<a href="#contact">CONTATO</a>
			<a href="#contact">ÁREA DO CLIENTE</a>
			<label for="checkbox" class="hide-menu-botton">				
				<i class="fas fa-times"></i>
			</label>
		</ul>
	</div>
</header>