<header>
	<div class="header">
		<a href="www.kaservicos.com.br"><img src="../assets/img/kalogo.png" class="logo-b"></a>

		<button class="button-proposal">Solicitar Proposta</button>
		<input type="checkbox" id="checkbox">	
		<label for="checkbox" class="show-menu-botton">
			<i class="fas fa-bars"></i>
		</label>

		<ul class="menu">
			<a href="#index.php">HOME</a>
			<a href="../views/about.php">SOBRE NÓS</a>
			<a href="index.php#box-tecs">SERVIÇOS</a>
			<a href=../views/cases.php>CASES</a>
			<a href="#">BLOG</a>
			<a href="index.php#contact">CONTATO</a>
			<a href="https://www.dominioatendimento.com:82/login.html" target="_blank">ÁREA DO CLIENTE</a>
			<label for="checkbox" class="hide-menu-botton">				
				<i class="fas fa-times"></i>
			</label>
		</ul>
	</div>
</header>