	<div class="contact-info">
	<a target=”_blank” href="https://api.whatsapp.com/send?phone=5571981072614&text=Ol%C3%A1!%20Encontrei%20a%20KA%20no%20site!">
		<div class="option">
			<i class="fab fa-whatsapp"></i>
			<div class="text">Converse pelo whatsapp</div>
		</div>
		</a>
		<div class="option">
			<i class="fas fa-envelope"></i>
			<div class="text">contato@kaservicos.com.br</div>
		</div>

	</div>